# Generated by Django 4.2 on 2026-02-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshapp', '0002_order_amount_order_paid_at_order_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
