# Generated by Django 4.2 on 2026-02-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshapp', '0005_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricetier',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
