# Generated by Django 4.2 on 2026-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshapp', '0006_productpricetier_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
